runtime: php82

env_variables:
  APP_NAME: Laravel
  APP_ENV: production
  APP_KEY: base64:UhQZ18c3Zhaxd+M3ZP1caDQcO4s3hwO3aXspZvfN/FI=
  APP_DEBUG: true
  APP_URL: https://sistem-laporan.ue.r.appspot.com  # Gantikan ikut domain App Engine bila dah deploy

  LOG_CHANNEL: stack
  LOG_DEPRECATIONS_CHANNEL: null
  LOG_LEVEL: debug

  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: sistem_laporan
  DB_USERNAME: root
  DB_PASSWORD: ""

  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  FILESYSTEM_DISK: local
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: file
  SESSION_LIFETIME: 120

  REDIS_HOST: 127.0.0.1
  REDIS_PASSWORD: null
  REDIS_PORT: 6379

  MAIL_MAILER: smtp
  MAIL_HOST: mailpit
  MAIL_PORT: 1025
  MAIL_USERNAME: null
  MAIL_PASSWORD: null
  MAIL_ENCRYPTION: null
  MAIL_FROM_ADDRESS: "hello@example.com"
  MAIL_FROM_NAME: "Laravel"

  AWS_DEFAULT_REGION: us-east-1
  AWS_USE_PATH_STYLE_ENDPOINT: false

  VITE_APP_NAME: "Laravel"

handlers:
  - url: /favicon.ico
    static_files: public/favicon.ico
    upload: public/favicon.ico

  - url: /(.+\.(css|js|ico|png|jpg|gif|svg|eot|ttf|woff|woff2))
    static_files: public/\1
    upload: public/(.+\.(css|js|ico|png|jpg|gif|svg|eot|ttf|woff|woff2))

  - url: /.*
    script: auto
